const DATA={config:null,glossary:[],artists:[],works:[],workshops:[],culturalObjects:[],pages:{},media:[]};
let INDEX={glossary:new Map(),artists:new Map(),works:new Map(),workshops:new Map(),objects:new Map(),media:new Map()};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>String(s??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const text=v=>Array.isArray(v)?v.join(' '):String(v??'');
function media(id){return INDEX.media.get(id)||null}
function imgPath(ref){
  if(!ref)return '';
  const id=String(ref).replace(/\.jpg$/i,'').replace(/\.webp$/i,'');
  const m=INDEX.media.get(id);
  if(m?.path)return m.path;
  return `assets/${id}.webp`;
}
function relationChips(ids,map,route,labelFn=x=>x.title||x.name||x){
  return (ids||[]).map(id=>{const x=map.get(id);if(!x)return '';const label=labelFn(x);return `<a class="chip" href="#/${route}/${encodeURIComponent(id)}">${esc(label)}</a>`}).join('');
}
function pageHead(title,sub=''){return `<div class="page-head"><h2>${esc(title)}</h2><p class="sub">${esc(sub)}</p></div>`}
function layout(content){
  const nav=[['Qui je suis','#/qui-je-suis'],['Documents de stage','#/stages'],['Ateliers','#/ateliers'],['Activités','#/activites'],['Préparations','#/preparations'],['Glossaire','#/glossaire'],['Références','#/artistes'],['Objets culturels','#/objets']];
  document.querySelector('#app').innerHTML=`<div class="app"><header class="top"><a class="logo" href="#/">Ma boîte à outils<br><small>de future maîtresse</small></a><nav class="nav">${nav.map(([t,h])=>`<a href="${h}">${t}</a>`).join('')}</nav><input id="global-search" class="search" placeholder="Rechercher…"></header><main>${content}</main><footer class="footer">Portfolio étudiant d’Audrey-Lita Sonnet · Architecture pensée pour être enrichie pendant toute la formation.</footer></div>`;
  const q=$('#global-search'); q.addEventListener('keydown',e=>{if(e.key==='Enter'&&q.value.trim())location.hash='#/recherche/'+encodeURIComponent(q.value.trim())});
  const cur=location.hash.split('/')[1]||''; document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href').includes(cur)));
}
function gallery(ids,missing=[]){
  const known=(ids||[]).map(id=>media(id)).filter(Boolean);
  if(!known.length&&!missing.length)return '';
  return `<div class="gallery">${known.map(m=>`<figure><img src="${esc(imgPath(m.id))}" alt=""><figcaption>${esc(m.caption||'')}</figcaption></figure>`).join('')}${(missing||[]).map(id=>`<div class="media-missing"><strong>Média indisponible</strong><span>${esc(id)}</span><small>Référencé dans la source PUBLISHED mais absent du checkpoint d’assets.</small></div>`).join('')}</div>`;
}
function home(){layout(`<section class="hero"><div><div class="eyebrow">Portfolio d’enseignement</div><h1>Bienvenue dans<br>ma boîte à outils</h1><p class="lead">Un espace vivant pour rassembler mes expériences, mes ateliers, mes préparations et mes ressources pour l’école.</p><p class="lead">Le contenu est organisé comme un réseau : une notion peut renvoyer à un atelier, un artiste, une œuvre ou une autre ressource.</p></div><div class="desk"><button class="object sage" onclick="location.hash='#/preparations'"><span>🎒</span><b>Préparations</b><small>Par matière, niveau, année</small></button><button class="object pink" onclick="location.hash='#/ateliers'"><span>🖌️</span><b>Ateliers</b><small>Expérimenter et documenter</small></button><button class="object blue" onclick="location.hash='#/activites'"><span>✂️</span><b>Activités</b><small>Musique, psychomotricité…</small></button><button class="object lilac" onclick="location.hash='#/glossaire'"><span>🔎</span><b>Glossaire</b><small>Notions et procédés</small></button><button class="object yellow" onclick="location.hash='#/artistes'"><span>🖼️</span><b>Références</b><small>Artistes et œuvres</small></button><button class="object sage" onclick="location.hash='#/qui-je-suis'"><span>🌱</span><b>Qui je suis</b><small>Parcours, CV, vision</small></button></div></section><section class="cards"><article class="card"><h3>Un portfolio évolutif</h3><p>Les contenus sont séparés de l’interface afin de pouvoir ajouter, modifier ou supprimer des ressources sans reconstruire le site.</p></article><article class="card"><h3>Des liens croisés</h3><p>Atelier → notion → artiste → œuvre, et retour vers les contenus associés.</p></article><article class="card"><h3>Une base déjà remplie</h3><p>${DATA.glossary.length} entrées de glossaire, ${DATA.artists.length} profils d’artistes, ${DATA.works.length} œuvres et ${DATA.workshops.length} ateliers.</p></article></section>`)}
function glossaryList(){let q='',typ='';const render=()=>{const arr=DATA.glossary.filter(x=>(!q||[x.title,x.type,...x.content].join(' ').toLowerCase().includes(q.toLowerCase()))&&(!typ||x.type===typ)).sort((a,b)=>a.title.localeCompare(b.title,'fr'));$('#glist').innerHTML=arr.map(x=>`<article class="item"><div class="type">${esc(x.type||'Ressource')}</div><h3><a class="link" href="#/glossaire/${x.id}">${esc(x.title)}</a></h3><p>${esc(x.content.slice(0,2).join(' '))}</p><div class="chips">${relationChips(x.workshopIds,INDEX.workshops,'ateliers')}</div></article>`).join('')||'<div class="empty">Aucun terme ne correspond.</div>'};layout(`${pageHead('Glossaire','Recherche, ordre alphabétique et relations croisées')}<div class="toolbar"><input id="gq" placeholder="Rechercher un terme…"><select id="gtype"><option value="">Tous les types</option>${[...new Set(DATA.glossary.map(x=>x.type).filter(Boolean))].sort().map(t=>`<option>${esc(t)}</option>`).join('')}</select></div><div id="glist" class="list"></div>`);$('#gq').addEventListener('input',e=>{q=e.target.value;render()});$('#gtype').addEventListener('change',e=>{typ=e.target.value;render()});render()}
function glossaryDetail(id){const x=INDEX.glossary.get(id);if(!x)return glossaryList();layout(`${pageHead(x.title,x.type||'Entrée du glossaire')}<a class="back" href="#/glossaire">← Retour au glossaire</a><article class="detail text">${linkify(x.content,'glossaire',id).map(p=>`<p>${p}</p>`).join('')}${x.sources?.length?`<h3>Sources</h3>${x.sources.map(s=>`<p>${esc(s)}</p>`).join('')}`:''}<h3>Connexions</h3><div class="chips">${relationChips(x.workshopIds,INDEX.workshops,'ateliers')}${relationChips(x.artistIds,INDEX.artists,'artistes',a=>a.name)}${relationChips(x.workIds,INDEX.works,'oeuvres',w=>w.title)}</div></article>`)}
function artists(){let q='';const render=()=>{const arr=DATA.artists.filter(x=>!q||[x.name,...x.bio,...x.workIds.map(id=>INDEX.works.get(id)?.title||'')].join(' ').toLowerCase().includes(q.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name,'fr'));$('#alist').innerHTML=arr.map(x=>`<article class="item">${x.mediaIds?.[0]?`<img src="${esc(imgPath(x.mediaIds[0]))}" alt="" style="width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:15px;margin-bottom:10px">`:''}<h3><a class="link" href="#/artistes/${x.id}">${esc(x.name)}</a></h3><p>${esc(x.bio.join(' ').slice(0,240))}</p><p><small>${x.workIds.length} œuvre${x.workIds.length>1?'s':''}</small></p></article>`).join('')||'<div class="empty">Aucun artiste trouvé.</div>'};layout(`${pageHead('Références artistiques','Artistes, œuvres, courants, médiums et procédés')}<div class="toolbar"><input id="aq" placeholder="Rechercher un artiste ou une œuvre…"></div><div id="alist" class="list"></div>`);$('#aq').addEventListener('input',e=>{q=e.target.value;render()});render()}
function artistDetail(id){const x=INDEX.artists.get(id);if(!x)return artists();const works=x.workIds.map(id=>INDEX.works.get(id)).filter(Boolean);layout(`${pageHead(x.name,'Biographie et œuvres')}<a class="back" href="#/artistes">← Retour aux références</a><article class="detail"><div class="profile">${x.mediaIds?.[0]?`<div><img class="profile-photo" src="${esc(imgPath(x.mediaIds[0]))}" alt="${esc(x.name)}"></div>`:'<div></div>'}<div><h2>${esc(x.name)}</h2><div class="text">${linkify(x.bio,'artistes',id).map(p=>`<p>${p}</p>`).join('')}</div></div></div><h3>Œuvres</h3>${works.map(w=>`<div class="work-card">${w.mediaIds?.length?gallery(w.mediaIds):''}<h4><a class="link" href="#/oeuvres/${w.id}">${esc(w.title||'Œuvre')}</a></h4><div class="meta">${[['Date',w.Date],['Siècle',w.Siècle],['Courant artistique',w['Courant artistique']],['Dimensions',w.Dimensions],['Médium',w.Médium],['Procédés artistiques',w['Procédés artistiques']]].filter(([,v])=>v).map(([k,v])=>`<div><strong>${esc(k)}</strong>${esc(v)}</div>`).join('')}</div></div>`).join('')||'<p>Aucune œuvre reliée.</p>'}<h3>Connexions</h3><div class="chips">${relationChips(x.glossaryIds,INDEX.glossary,'glossaire')}${relationChips(x.workshopIds,INDEX.workshops,'ateliers')}</div></article>`)}
function worksList(){let q='';const render=()=>{const arr=DATA.works.filter(x=>!q||[x.title,x.artist,x['Courant artistique'],x.Médium,x['Procédés artistiques']].join(' ').toLowerCase().includes(q.toLowerCase())).sort((a,b)=>a.title.localeCompare(b.title,'fr'));$('#wlist').innerHTML=arr.map(x=>`<article class="item"><h3><a class="link" href="#/oeuvres/${x.id}">${esc(x.title)}</a></h3><p>${esc(x.artist||'')}</p><div class="chips">${x.artistId&&INDEX.artists.get(x.artistId)?`<a class="chip" href="#/artistes/${x.artistId}">${esc(INDEX.artists.get(x.artistId).name)}</a>`:''}${relationChips(x.workshopIds,INDEX.workshops,'ateliers')}</div></article>`).join('')||'<div class="empty">Aucune œuvre trouvée.</div>'};layout(`${pageHead('Œuvres','Œuvres séparées des profils d’artistes')}<div class="toolbar"><input id="wq" placeholder="Rechercher une œuvre, un artiste, un médium…"></div><div id="wlist" class="list"></div>`);$('#wq').addEventListener('input',e=>{q=e.target.value;render()});render()}
function workDetail(id){const x=INDEX.works.get(id);if(!x)return worksList();layout(`${pageHead(x.title,'Œuvre')}<a class="back" href="#/oeuvres">← Retour aux œuvres</a><article class="detail">${x.mediaIds?.length?gallery(x.mediaIds):''}<h2>${esc(x.title)}</h2><div class="meta">${[['Artiste',x.artist],['Date',x.Date],['Siècle',x.Siècle],['Courant artistique',x['Courant artistique']],['Dimensions',x.Dimensions],['Médium',x.Médium],['Procédés artistiques',x['Procédés artistiques']]].filter(([,v])=>v).map(([k,v])=>`<div><strong>${esc(k)}</strong>${esc(v)}</div>`).join('')}</div>${x.notes?.length?`<div class="text">${linkify(x.notes,'oeuvres',id).map(n=>`<p>${n}</p>`).join('')}</div>`:''}<h3>Connexions</h3><div class="chips">${x.artistId&&INDEX.artists.get(x.artistId)?`<a class="chip" href="#/artistes/${x.artistId}">${esc(INDEX.artists.get(x.artistId).name)}</a>`:''}${relationChips(x.glossaryIds,INDEX.glossary,'glossaire')}${relationChips(x.workshopIds,INDEX.workshops,'ateliers')}</div></article>`)}
function workshops(){layout(`${pageHead('Ateliers d’expérimentations','Les ateliers sont repris depuis la source PUBLISHED et reliés aux autres collections')}<div class="list">${DATA.workshops.map(x=>`<article class="item"><h3><a class="link" href="#/ateliers/${x.id}">${esc(x.title)}</a></h3><p>${esc(text(x.intro).slice(0,300))}</p><div class="chips">${relationChips(x.glossaryIds,INDEX.glossary,'glossaire')}${relationChips(x.artistIds,INDEX.artists,'artistes',a=>a.name)}</div></article>`).join('')}</div>`)}
function workshopDetail(id){const x=INDEX.workshops.get(id);if(!x)return workshops();layout(`${pageHead(x.title,'Atelier documenté')}<a class="back" href="#/ateliers">← Retour aux ateliers</a><article class="detail">${x.intro?.length?`<div class="text">${linkify(x.intro,'ateliers',id).map(p=>`<p>${p}</p>`).join('')}</div>`:''}${x.mediaIds?.length?gallery(x.mediaIds):''}${x.sections.map(s=>`<section><h3>${esc(s.heading||'Contenu')}</h3>${s.content?.length?linkify(s.content,'ateliers',id).map(p=>`<p>${p}</p>`).join(''):''}${s.images?.length?gallery(s.images):''}</section>`).join('')} ${x.missingMediaIds?.length?gallery([],x.missingMediaIds):''}<h3>Éléments du glossaire</h3><div class="chips">${relationChips(x.glossaryIds,INDEX.glossary,'glossaire')}</div>${x.artistIds?.length?`<h3>Références artistiques</h3><div class="chips">${relationChips(x.artistIds,INDEX.artists,'artistes',a=>a.name)}</div>`:''}</article>`)}
function objects(){layout(`${pageHead('Objets culturels','Références culturelles reliées aux notions et aux pratiques')}<div class="list">${DATA.culturalObjects.map(x=>`<article class="item">${x.mediaIds?.[0]?`<img src="${esc(imgPath(x.mediaIds[0]))}" alt="" style="width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:15px;margin-bottom:10px">`:''}<h3>${esc(x.title)}</h3><p>${linkify([(x.content||[]).slice(0,2).join(' ')],'objets',x.id).join('')}</p><div class="chips">${relationChips(x.glossaryIds,INDEX.glossary,'glossaire')}${relationChips(x.workshopIds,INDEX.workshops,'ateliers')}</div></article>`).join('')}</div>`)}
function activities(){layout(`${pageHead('Activités','Ressources pratiques classées par domaine')}<div class="cards"><article class="card"><h3>🎵 Musique</h3><p>Chants et ressources de musique déjà présents dans le site source.</p><a class="link" href="#/activites/chants">Voir les chants →</a></article><article class="card"><h3>🤸 Psychomotricité</h3><p>Activités et séance observée en maternelle.</p><a class="link" href="#/activites/psychomotricite">Voir la ressource →</a></article><article class="card"><h3>🎨 Arts plastiques</h3><p>Les ateliers d’expérimentations sont regroupés dans leur section dédiée.</p><a class="link" href="#/ateliers">Voir les ateliers →</a></article></div>`)}
function activityDetail(kind){const x=DATA.pages[kind];if(!x)return activities();layout(`${pageHead(x.title,'Activité')}<a class="back" href="#/activites">← Retour aux activités</a><article class="detail text">${esc(x.text||'').split(/(?<=\.)\s+(?=[A-ZÀÉÈ])/).map(p=>`<p>${p}</p>`).join('')}</article>`)}
function preparations(){const x=DATA.pages.preparation||{};layout(`${pageHead('Fiches de préparation','Une bibliothèque destinée à être enrichie par matière, niveau, année et type')}<article class="detail text"><h3>Préparation existante</h3>${esc(x.text||'').split(/(?<=\.)\s+(?=[A-ZÀÉÈ])/).map(p=>`<p>${p}</p>`).join('')}<div class="notice empty">La structure est prête pour ajouter d’autres fiches sans modifier l’interface : matière → niveau → année → type → objectifs → déroulement → matériel → évaluation.</div></article>`)}
function stages(){const x=DATA.pages.stage||{};layout(`${pageHead('Documents de stage','CV, lettres et documents liés aux expériences de terrain')}<article class="detail text"><h3>Documents</h3><p>${esc(x.text||'').slice(0,500)}</p><div class="pdfs"><a class="pdf" href="documents/CV-Audrey-Lita-Sonnet-2026.pdf" target="_blank">📄 CV 2026</a><a class="pdf" href="documents/Lettre-de-motivation-2e-annee.pdf" target="_blank">📄 Lettre de motivation · 2e année</a></div><h3>Stages à venir</h3><p>Cette section est prévue pour accueillir chaque nouvelle expérience : école, niveau, contexte, préparations, analyses, productions et documents.</p></article>`)}
function identity(){const p=DATA.pages.home||{};layout(`${pageHead('Qui je suis','Parcours, CV et lettre de motivation')}<article class="detail"><h3>Mon parcours</h3>${esc(p.text||'').split(/(?<=\.)\s+(?=[A-ZÀÉÈ])/).slice(0,5).map(t=>`<p>${t}</p>`).join('')}<div class="pdfs"><a class="pdf" href="documents/CV-Audrey-Lita-Sonnet-2026.pdf" target="_blank">📄 Voir mon CV</a><a class="pdf" href="documents/Lettre-de-motivation-2e-annee.pdf" target="_blank">📄 Lettre de motivation</a></div><h3>Ma vision de l’école</h3><p>Ma réflexion sur l’inclusion, les classes à niveaux multiples et la place de l’enfant dans la communauté scolaire.</p><p><a class="link" href="#/vision">Lire ma vision →</a></p></article>`)}
function vision(){const t=DATA.pages.home?.text||'';const i=t.indexOf("Ma vision de l'école"),j=t.indexOf('Qui suis-je ?');const v=i>=0?t.slice(i+"Ma vision de l'école".length,j>=0?j:t.length):t;layout(`${pageHead('Ma vision de l’école','Une page éditoriale indépendante')}<article class="detail text">${esc(v).split(/(?<=\.)\s+(?=[A-ZÀÉÈ])/).filter(Boolean).map(p=>`<p>${p}</p>`).join('')}</article>`)}
function searchPage(q){const needle=q.toLowerCase();const terms=DATA.glossary.filter(x=>[x.title,x.type,...x.content].join(' ').toLowerCase().includes(needle)).slice(0,10);const arts=DATA.artists.filter(x=>[x.name,...x.bio].join(' ').toLowerCase().includes(needle)).slice(0,10);const ws=DATA.workshops.filter(x=>[x.title,...x.intro].join(' ').toLowerCase().includes(needle)).slice(0,10);const works=DATA.works.filter(x=>[x.title,x.artist,x.Médium,x['Courant artistique'],x['Procédés artistiques']].join(' ').toLowerCase().includes(needle)).slice(0,10);layout(`${pageHead('Recherche',`Résultats pour « ${q} »`)}<div class="cards"><article class="card"><h3>Glossaire</h3>${terms.map(x=>`<p><a class="link" href="#/glossaire/${x.id}">${esc(x.title)}</a></p>`).join('')||'<p>Aucun résultat.</p>'}</article><article class="card"><h3>Artistes</h3>${arts.map(x=>`<p><a class="link" href="#/artistes/${x.id}">${esc(x.name)}</a></p>`).join('')||'<p>Aucun résultat.</p>'}</article><article class="card"><h3>Œuvres</h3>${works.map(x=>`<p><a class="link" href="#/oeuvres/${x.id}">${esc(x.title)}</a></p>`).join('')||'<p>Aucun résultat.</p>'}</article><article class="card"><h3>Ateliers</h3>${ws.map(x=>`<p><a class="link" href="#/ateliers/${x.id}">${esc(x.title)}</a></p>`).join('')||'<p>Aucun résultat.</p>'}</article></div>`)}
function router(){const h=decodeURIComponent(location.hash||'#/');const parts=h.replace(/^#\/?/,'').split('/').filter(Boolean);if(!parts.length)return home();const [r,id]=parts;if(r==='glossaire')return id?glossaryDetail(id):glossaryList();if(r==='artistes')return id?artistDetail(id):artists();if(r==='oeuvres')return id?workDetail(id):worksList();if(r==='ateliers')return id?workshopDetail(id):workshops();if(r==='objets')return objects();if(r==='activites')return id?activityDetail(id):activities();if(r==='preparations')return preparations();if(r==='qui-je-suis')return identity();if(r==='vision')return vision();if(r==='stages')return stages();if(r==='recherche')return searchPage(id||'');return home()}
let LINK_INDEX=[], LINK_RE=null;
function escRe(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function buildLinkIndex(){
  const items=[];
  for(const x of DATA.glossary||[]) if(x.title && x.title.length>=4) items.push({name:x.title,route:'glossaire',id:x.id});
  for(const x of DATA.artists||[]) if(x.name && x.name.length>=4) items.push({name:x.name,route:'artistes',id:x.id});
  for(const x of DATA.works||[]) if(x.title && x.title.length>=4) items.push({name:x.title,route:'oeuvres',id:x.id});
  for(const x of DATA.workshops||[]) if(x.title && x.title.length>=4) items.push({name:x.title,route:'ateliers',id:x.id});
  items.sort((a,b)=>b.name.length-a.name.length);
  LINK_INDEX=items;
  const seenNames=new Set(),alts=[];
  for(const it of items){const en=esc(it.name);if(!seenNames.has(en)){seenNames.add(en);alts.push(escRe(en))}}
  LINK_RE = alts.length ? new RegExp('(^|[^\\w\\u00C0-\\u017F])('+alts.join('|')+')(?=[^\\w\\u00C0-\\u017F]|$)','gi') : null;
}
function linkify(paragraphs, currentRoute, currentId){
  if(!LINK_RE) return (paragraphs||[]).map(esc);
  const byEsc=new Map();
  for(const it of LINK_INDEX){const en=esc(it.name).toLowerCase();if(!byEsc.has(en))byEsc.set(en,it)}
  const used=new Set();
  return (paragraphs||[]).map(raw=>{
    const s=esc(raw);
    return s.replace(LINK_RE,(m,pre,name)=>{
      const it=byEsc.get(name.toLowerCase());
      if(!it)return m;
      if(it.route===currentRoute && it.id===currentId)return m;
      const key=it.route+':'+it.id;
      if(used.has(key))return m;
      used.add(key);
      return `${pre}<a class="link" href="#/${it.route}/${it.id}">${name}</a>`;
    });
  });
}
async function load(){try{const config=await fetch('config/site.json').then(r=>{if(!r.ok)throw new Error('config/site.json introuvable');return r.json()});DATA.config=config;const loaded=await Promise.all(config.dataCollections.map(c=>fetch(c.file).then(r=>{if(!r.ok)throw new Error(`Impossible de charger ${c.file}`);return r.json()}).then(v=>[c.id,v])));for(const [id,v] of loaded)DATA[id]=v;INDEX.glossary=new Map(DATA.glossary.map(x=>[x.id,x]));INDEX.artists=new Map(DATA.artists.map(x=>[x.id,x]));INDEX.works=new Map(DATA.works.map(x=>[x.id,x]));INDEX.workshops=new Map(DATA.workshops.map(x=>[x.id,x]));INDEX.objects=new Map(DATA.culturalObjects.map(x=>[x.id,x]));INDEX.media=new Map(DATA.media.map(x=>[x.id,x]));buildLinkIndex();router();window.addEventListener('hashchange',router)}catch(err){document.querySelector('#app').innerHTML=`<main class="detail text"><h2>Impossible de charger la boîte à outils</h2><p>${esc(err.message)}</p><p>Vérifie que le site est servi depuis la racine du projet afin que <code>config/site.json</code> soit accessible.</p></main>`;console.error(err)}}
load();
