const DATA={};
const nav=[['Accueil','#/'],['Qui je suis','#/qui-je-suis'],['Documents de stage','#/stages'],['Ateliers','#/ateliers'],['Activités','#/activites'],['Préparations','#/preparations'],['Glossaire','#/glossaire'],['Références','#/artistes'],['Objets culturels','#/objets']];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>String(s).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function imgPath(b){return b?`assets/webp/${b.replace(/\.jpg$/i,'.webp')}`:''}
function linkify(text){
 let out=esc(text);
 const all=[...DATA.glossaire.map(x=>({t:x.title,h:`#/glossaire/${x.id}`})),...DATA.artistes.map(x=>({t:x.name,h:`#/artistes/${x.id}`}))].sort((a,b)=>b.t.length-a.t.length);
 for(const x of all){const re=new RegExp(`(?<![\\w-])(${x.t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})(?![\\w-])`,'gi'); out=out.replace(re,`<a class="link" href="${x.h}">$1</a>`)}
 return out;
}
function layout(content){document.querySelector('#app').innerHTML=`<div class="app"><header class="top"><a class="logo" href="#/">Ma boîte à outils<br><small>de future maîtresse</small></a><nav class="nav">${nav.slice(1).map(([t,h])=>`<a href="${h}">${t}</a>`).join('')}</nav><input id="global-search" class="search" placeholder="Rechercher…"></header><main>${content}</main><footer class="footer">Portfolio étudiant d'Audrey-Lita Sonnet · Architecture pensée pour être enrichie pendant toute la formation.</footer></div>`; const q=$('#global-search'); q.addEventListener('keydown',e=>{if(e.key==='Enter'&&q.value.trim()) location.hash='#/recherche/'+encodeURIComponent(q.value.trim())});
 const cur=location.hash.split('/')[1]||''; document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href').includes(cur)));
}
function pageHead(title,sub=''){return `<div class="page-head"><h2>${esc(title)}</h2><p class="sub">${esc(sub)}</p></div>`}
function home(){layout(`<section class="hero"><div><div class="eyebrow">Portfolio d’enseignement</div><h1>Bienvenue dans<br>ma boîte à outils</h1><p class="lead">Un espace vivant pour rassembler mes expériences, mes ateliers, mes préparations et mes ressources pour l’école.</p><p class="lead">Le contenu est organisé comme un réseau : une notion peut renvoyer à un atelier, un artiste, une œuvre ou une autre ressource.</p></div><div class="desk"><button class="object sage" onclick="location.hash='#/preparations'"><span>🎒</span><b>Préparations</b><small>Par matière, niveau, année</small></button><button class="object pink" onclick="location.hash='#/ateliers'"><span>🖌️</span><b>Ateliers</b><small>Expérimenter et documenter</small></button><button class="object blue" onclick="location.hash='#/activites'"><span>✂️</span><b>Activités</b><small>Musique, psychomotricité…</small></button><button class="object lilac" onclick="location.hash='#/glossaire'"><span>🔎</span><b>Glossaire</b><small>Notions et procédés</small></button><button class="object yellow" onclick="location.hash='#/artistes'"><span>🖼️</span><b>Références</b><small>Artistes et œuvres</small></button><button class="object sage" onclick="location.hash='#/qui-je-suis'"><span>🌱</span><b>Qui je suis</b><small>Parcours, CV, vision</small></button></div></section><section class="cards"><article class="card"><h3>Un portfolio évolutif</h3><p>Les contenus sont séparés de l’interface afin de pouvoir ajouter, modifier ou supprimer des ressources sans reconstruire le site.</p></article><article class="card"><h3>Des liens croisés</h3><p>Atelier → notion → artiste → œuvre, et retour vers les contenus associés.</p></article><article class="card"><h3>Une base déjà remplie</h3><p>${DATA.glossaire.length} entrées de glossaire, ${DATA.artistes.length} profils d’artistes et ${DATA.ateliers.length} ateliers issus de ton export.</p></article></section>`)}
function glossaryList(){let q='',filtered=DATA.glossaire; const render=()=>{filtered=DATA.glossaire.filter(x=>!q||[x.title,x.type,...x.content].join(' ').toLowerCase().includes(q.toLowerCase()));$('#glist').innerHTML=filtered.map(x=>`<article class="item"><div class="type">${esc(x.type||'Ressource')}</div><h3><a class="link" href="#/glossaire/${x.id}">${esc(x.title)}</a></h3><p>${esc(x.content.slice(0,2).join(' '))}</p><div class="chips">${x.ateliers.slice(0,4).map(a=>`<a class="chip" href="#/ateliers/${slug(a)}">${esc(a)}</a>`).join('')}</div></article>`).join('')||'<div class="empty">Aucun terme ne correspond.</div>'}; layout(`${pageHead('Glossaire','Recherche, ordre alphabétique et relations croisées')}<div class="toolbar"><input id="gq" placeholder="Rechercher un terme…"><select id="gtype"><option value="">Tous les types</option><option>Notion plastique</option><option>Procédé plastique</option><option>Outil / matériel</option></select></div><div id="glist" class="list"></div>`);$('#gq').addEventListener('input',e=>{q=e.target.value;render()});$('#gtype').addEventListener('change',e=>{const typ=e.target.value;filtered=DATA.glossaire.filter(x=>(!q||[x.title,x.type,...x.content].join(' ').toLowerCase().includes(q.toLowerCase()))&&(!typ||x.type===typ));$('#glist').innerHTML=filtered.map(x=>`<article class="item"><div class="type">${esc(x.type||'Ressource')}</div><h3><a class="link" href="#/glossaire/${x.id}">${esc(x.title)}</a></h3><p>${esc(x.content.slice(0,2).join(' '))}</p></article>`).join('')||'<div class="empty">Aucun terme ne correspond.</div>'});render()}
function glossaryDetail(id){const x=DATA.glossaire.find(x=>x.id===id);if(!x)return glossaryList();layout(`${pageHead(x.title,x.type||'Entrée du glossaire')}<a class="back" href="#/glossaire">← Retour au glossaire</a><article class="detail text">${x.content.map(p=>`<p>${linkify(p)}</p>`).join('')} ${x.sources.length?`<h3>Sources</h3>${x.sources.map(s=>`<p>${esc(s)}</p>`).join('')}`:''}${x.ateliers.length?`<h3>Ateliers en lien</h3><div class="chips">${x.ateliers.map(a=>`<a class="chip" href="#/ateliers/${slug(a)}">${esc(a)}</a>`).join('')}</div>`:''}</article>`)}
function artists(){let q='';const render=()=>{const arr=DATA.artistes.filter(x=>!q||[x.name,...x.bio,x.works.map(w=>Object.values(w).join(' '))].join(' ').toLowerCase().includes(q.toLowerCase()));$('#alist').innerHTML=arr.map(x=>`<article class="item">${x.images[0]?`<img src="${imgPath(x.images[0])}" alt="" style="width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:15px;margin-bottom:10px">`:''}<h3><a class="link" href="#/artistes/${x.id}">${esc(x.name)}</a></h3><p>${esc(x.bio.join(' ').slice(0,240))}</p><p><small>${x.works.length} œuvre${x.works.length>1?'s':''}</small></p></article>`).join('')||'<div class="empty">Aucun artiste trouvé.</div>'};layout(`${pageHead('Références artistiques','Artistes, œuvres, courants, médiums et procédés')}<div class="toolbar"><input id="aq" placeholder="Rechercher un artiste ou une œuvre…"></div><div id="alist" class="list"></div>`);$('#aq').addEventListener('input',e=>{q=e.target.value;render()});render()}
function artistDetail(id){const x=DATA.artistes.find(x=>x.id===id);if(!x)return artists();layout(`${pageHead(x.name,'Biographie et œuvres')}<a class="back" href="#/artistes">← Retour aux références</a><article class="detail"><div class="profile">${x.images[0]?`<div><img class="profile-photo" src="${imgPath(x.images[0])}" alt="${esc(x.name)}"></div>`:'<div></div>'}<div><h2>${esc(x.name)}</h2><div class="text">${x.bio.map(p=>`<p>${esc(p)}</p>`).join('')}</div></div></div><h3>Œuvres</h3>${x.works.map((w,i)=>`<div class="work-card">${x.images[i]?`<img src="${imgPath(x.images[i])}" alt="" style="width:100%;max-height:520px;object-fit:contain;border-radius:15px;margin-bottom:12px">`:''}<h4>${esc(w.title||'Œuvre')}</h4><div class="meta">${['Date','Siècle','Courant artistique','Dimensions','Médium','Procédés artistiques'].filter(k=>w[k]).map(k=>`<div><strong>${esc(k)}</strong>${esc(w[k])}</div>`).join('')}</div>${w.notes?`<p>${w.notes.map(esc).join(' ')}</p>`:''}</div>`).join('')}<h3>Connexions</h3><div class="chips">${x.glossary.map(g=>`<a class="chip" href="#/glossaire/${slug(g)}">${esc(g)}</a>`).join('')}${x.ateliers.map(a=>`<a class="chip" href="#/ateliers/${slug(a)}">${esc(a)}</a>`).join('')}</div></article>`)}
function workshops(){layout(`${pageHead('Ateliers d’expérimentations','Les ateliers existants sont repris et reliés au glossaire et aux références')}<div class="list">${DATA.ateliers.map(x=>`<article class="item"><h3><a class="link" href="#/ateliers/${x.id}">${esc(x.title)}</a></h3><p>${esc(x.sections.slice(0,2).flatMap(s=>s.items).slice(0,2).join(' '))}</p><div class="chips">${x.glossary.slice(0,6).map(g=>`<a class="chip" href="#/glossaire/${slug(g)}">${esc(g)}</a>`).join('')}</div></article>`).join('')}</div>`)}
function workshopDetail(id){const x=DATA.ateliers.find(x=>x.id===id);if(!x)return workshops();layout(`${pageHead(x.title,'Atelier documenté')}<a class="back" href="#/ateliers">← Retour aux ateliers</a><article class="detail">${x.images.length?`<div class="gallery">${x.images.map(i=>`<img src="${imgPath(i)}" alt="">`).join('')}</div>`:''}${x.sections.map(s=>`<section><h3>${esc(s.label||'Contenu')}</h3>${s.items.map(p=>`<p>${linkify(p)}</p>`).join('')}</section>`).join('')}<h3>Éléments du glossaire</h3><div class="chips">${x.glossary.map(g=>`<a class="chip" href="#/glossaire/${slug(g)}">${esc(g)}</a>`).join('')}</div>${x.artists.length?`<h3>Références artistiques</h3><div class="chips">${x.artists.map(a=>`<a class="chip" href="#/artistes/${slug(a)}">${esc(a)}</a>`).join('')}</div>`:''}</article>`)}
function objects(){layout(`${pageHead('Objets culturels','Références culturelles reliées aux notions et aux pratiques')}<div class="list">${DATA.objets.map(x=>`<article class="item">${x.images[0]?`<img src="${imgPath(x.images[0])}" alt="" style="width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:15px;margin-bottom:10px">`:''}<h3>${esc(x.title)}</h3><p>${esc(x.content.slice(0,2).join(' '))}</p></article>`).join('')}</div>`)}
function activities(){const p=DATA.pages;layout(`${pageHead('Activités','Ressources pratiques classées par domaine')}<div class="cards"><article class="card"><h3>🎵 Musique</h3><p>Chants et ressources de musique déjà présents dans le site source.</p><a class="link" href="#/activites/chants">Voir les chants →</a></article><article class="card"><h3>🤸 Psychomotricité</h3><p>Activités et séance observée en maternelle.</p><a class="link" href="#/activites/psychomotricite">Voir la ressource →</a></article><article class="card"><h3>🎨 Arts plastiques</h3><p>Les ateliers d’expérimentations sont regroupés dans leur section dédiée.</p><a class="link" href="#/ateliers">Voir les ateliers →</a></article></div>`)}
function activityDetail(kind){const x=DATA.pages[kind];layout(`${pageHead(x.title,'Activité')}<a class="back" href="#/activites">← Retour aux activités</a><article class="detail text">${x.text.split(/(?<=\.)\s+(?=[A-ZÀÉÈ])/).map(p=>`<p>${esc(p)}</p>`).join('')}</article>`)}
function preparations(){const x=DATA.pages.preparation;layout(`${pageHead('Fiches de préparation','Une bibliothèque destinée à être enrichie par matière, niveau, année et type')}<article class="detail text"><h3>Préparation existante</h3>${x.text.split(/(?<=\.)\s+(?=[A-ZÀÉÈ])/).map(p=>`<p>${esc(p)}</p>`).join('')}<div class="notice empty">La structure est prête pour ajouter d’autres fiches sans modifier l’interface : matière → niveau → année → type → objectifs → déroulement → matériel → évaluation.</div></article>`)}
function stages(){const x=DATA.pages.stage;layout(`${pageHead('Documents de stage','CV, lettres et documents liés aux expériences de terrain')}<article class="detail text"><h3>Documents</h3><p>${esc(x.text.slice(0,500))}</p><div class="pdfs"><a class="pdf" href="documents/CV-Audrey-Lita-Sonnet-2026.pdf" target="_blank">📄 CV 2026</a><a class="pdf" href="documents/Lettre-de-motivation-2e-annee.pdf" target="_blank">📄 Lettre de motivation · 2e année</a></div><h3>Stages à venir</h3><p>Cette section est prévue pour accueillir chaque nouvelle expérience : école, niveau, contexte, préparations, analyses, productions et documents.</p></article>`)}
function vision(){const text=DATA.pages.home.text; const i=text.indexOf('Ma vision de l\'école'); const j=text.indexOf('Qui suis-je ?'); const v=i>=0?text.slice(i+'Ma vision de l\'école'.length,j>=0?j:text.length):text; layout(`${pageHead('Ma vision de l’école','Une page éditoriale indépendante')}<article class="detail text">${v.split(/(?<=\.)\s+(?=[A-ZÀÉÈ])/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('')}</article>`)}
function identity(){const p=DATA.pages.home;layout(`${pageHead('Qui je suis','Parcours, CV et lettre de motivation')}<article class="detail"><h3>Mon parcours</h3>${p.text.split(/(?<=\.)\s+(?=[A-ZÀÉÈ])/).slice(0,5).map(t=>`<p>${esc(t)}</p>`).join('')}<div class="pdfs"><a class="pdf" href="documents/CV-Audrey-Lita-Sonnet-2026.pdf" target="_blank">📄 Voir mon CV</a><a class="pdf" href="documents/Lettre-de-motivation-2e-annee.pdf" target="_blank">📄 Lettre de motivation</a></div><h3>Ma vision de l’école</h3><p>Ma réflexion sur l’inclusion, les classes à niveaux multiples et la place de l’enfant dans la communauté scolaire.</p><p><a class="link" href="#/vision">Lire ma vision →</a></p></article>`)}
function searchPage(q){const terms=DATA.glossaire.filter(x=>[x.title,...x.content].join(' ').toLowerCase().includes(q.toLowerCase())).slice(0,8);const arts=DATA.artistes.filter(x=>[x.name,...x.bio].join(' ').toLowerCase().includes(q.toLowerCase())).slice(0,8);layout(`${pageHead('Recherche',`Résultats pour « ${q} »`)}<div class="cards"><article class="card"><h3>Glossaire</h3>${terms.map(x=>`<p><a class="link" href="#/glossaire/${x.id}">${esc(x.title)}</a></p>`).join('')||'<p>Aucun résultat.</p>'}</article><article class="card"><h3>Artistes</h3>${arts.map(x=>`<p><a class="link" href="#/artistes/${x.id}">${esc(x.name)}</a></p>`).join('')||'<p>Aucun résultat.</p>'}</article></div>`)}
function router(){const h=decodeURIComponent(location.hash||'#/');const parts=h.replace(/^#\/?/,'').split('/').filter(Boolean);if(!parts.length)return home();const [r,id]=parts;if(r==='glossaire')return id?glossaryDetail(id):glossaryList();if(r==='artistes')return id?artistDetail(id):artists();if(r==='ateliers')return id?workshopDetail(id):workshops();if(r==='objets')return objects();if(r==='activites')return id?activityDetail(id):activities();if(r==='preparations')return preparations();if(r==='qui-je-suis')return identity();if(r==='vision')return vision();if(r==='stages')return stages();if(r==='recherche')return searchPage(id||'');return home()}
Promise.all(['glossaire','artistes','objets-culturels'].map(n=>fetch(`data/${n}.json`).then(r=>r.json()))).then(([g,a,o])=>{DATA.glossaire=g;DATA.artistes=a;DATA.objets=o;return fetch('data/ateliers.json').then(r=>r.json())}).then(w=>{DATA.ateliers=w;return fetch('data/pages.json').then(r=>r.json())}).then(p=>{DATA.pages=p;router();window.addEventListener('hashchange',router)});
